fix: update ESP-IDF 5.4 -> 5.4.1
Because that fixes espressif/esp-idf#15167: undefined reference to
`__atomic_test_and_set` when using `std::atomic_flag`.